### PR TITLE
Initial deep learning environment setup

### PR DESCRIPTION
**Pull request by hectcastro**
See `README` in this commit for details.

### CODE REVIEW

**Comment by hectcastro** [comment]
This is ready for attempted use. I'd like to try and iron out the issues we encounter using this setup before going down an AMI or container image publishing route.

**Comment by jerheff** [comment]
I'm wondering whether we should setup the default Theano config as a file or not.  The normal way of doing this is a file in the user's home directory such as ~/.theanorc 

The contents would be like below, key points of which include:

- throwing an error if the gpu is not used
- throwing an error if the cudnn library is not available
- forces the use of openblas
- enables better memory management on the GPU
- speeds some math

[global]
floatX = float32
device = gpu
force_device = True
allow_gc = False
mode = FAST_RUN
optimizer_including=cudnn

[blas]
ldflag = -lopenblas

[nvcc]
fastmath = True

[lib]
cnmem = 0.95

[DebugMode]
check_finite=1

**Comment by jerheff** [comment]
Add unzip to system packages installed in the container.  I couldn't figure out how to install packages after the fact in the container.

I also am unsure of how to move files into the container other than downloading them from a URL.  I could scp the files to the host, but that won't end up inside the container.

**Comment by hectcastro** [comment]
> Add unzip to system packages installed in the container. I couldn't figure out how to install packages after the fact in the container.

It should allow you to install new packages via APT after an `apt-get update`.

> I also am unsure of how to move files into the container other than downloading them from a URL. I could scp the files to the host, but that won't end up inside the container.

I've used `docker cp` for this from my local workstation:

```bash
$ docker cp somefile.txt 0b8ef4f2e684:/root
```

**Comment by hectcastro** [comment]
The `.theanorc` and `upzip` have been added to the image. In addition, I pushed the current state of the `Dockerfile` to Quay. It can be referenced with `quay.io/azavea/deep-learning:latest`.

**Pull request merged**
